title: James Long
theme: minima
author: jlonger13
email: jl9488@nyu.edu
description: > # this means to ignore newlines until "baseurl:"
  This is my website thatt reflects my accomplishments, projects, and goals.

# social links
twitter_username: @jlonger13
github_username:  @jlonger13

show_excerpts: true # set to false to remove excerpts on the homepage
